// Add New User
export const REQUEST_CREATE_NEW_USER = "REQUEST_CREATE_NEW_USER";
export const RECEIVE_CREATE_NEW_USER = "RECEIVE_CREATE_NEW_USER";
export const NEW_USER_CREATE_ERROR = "NEW_USER_CREATE_ERROR";
